#!/bin/bash

echo "🔒 SecureAuth AI - Quick RLS Fix"
echo "================================="
echo ""
echo "❌ Error: 'new row violates row-level security policy for table \"users\"'"
echo ""
echo "🔧 This happens because the RLS policies are too restrictive for user registration."
echo ""
echo "📋 Quick Fix Steps:"
echo ""
echo "1. Go to Supabase Dashboard: https://supabase.com/dashboard"
echo "2. Select your project: eociqzjowzjfxpvpupjr"
echo "3. Go to SQL Editor (left sidebar)"
echo "4. Create a new query"
echo "5. Copy and paste this SQL:"
echo ""
echo "----------------------------------------"
cat supabase/fix-rls.sql
echo "----------------------------------------"
echo ""
echo "6. Click 'Run' to execute"
echo "7. Refresh your application"
echo ""
echo "✅ This will fix the RLS policy issue and allow user registration!"
echo ""
echo "🚀 Alternative: Run the complete schema setup"
echo "   ./setup-database.sh"
echo ""
echo "Press Enter to continue..."
read
